# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-26 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nauczyciel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Przedmiot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=140)),
                ('nauczyciel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='szkola.Nauczyciel')),
            ],
        ),
        migrations.CreateModel(
            name='Uczen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=40)),
                ('przedmioty', models.ManyToManyField(to='szkola.Przedmiot')),
            ],
        ),
    ]
