# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szkola', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='przedmiot',
            name='nauczyciel',
        ),
        migrations.AddField(
            model_name='nauczyciel',
            name='przedmioty',
            field=models.ManyToManyField(to='szkola.Przedmiot'),
        ),
    ]
